# Generated by Django 3.2 on 2025-03-14 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False, help_text='Whether User is an Admin', verbose_name='Admin Status')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether user should have Staff Priveleges', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether user should be treated as active', verbose_name='Active')),
                ('learner', models.BooleanField(default=False, help_text='Whether user is a learner', verbose_name='Learner')),
                ('tutor', models.BooleanField(default=False, help_text='Whether user is a tutor', verbose_name='Tutor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('about', models.TextField(blank=True)),
                ('user_image', models.ImageField(blank=True, upload_to='userimages')),
                ('learning_level', models.CharField(blank=True, max_length=50, null=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
