# Generated by Django 3.2 on 2025-03-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20250325_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='ai_change',
            field=models.TextField(blank=True, help_text='Changes made to this quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint for improvement'),
        ),
    ]
