# Generated by Django 3.2 on 2025-06-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='course',
        ),
        migrations.AddField(
            model_name='discussion',
            name='lesson',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_lesson', to='learning.lesson'),
            preserve_default=False,
        ),
    ]
