# Generated by Django 3.2 on 2025-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20250617_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
