# Generated by Django 3.2 on 2025-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_quizresult_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
