# Generated by Django 3.2 on 2025-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
