# Generated by Django 3.2 on 2025-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_payment_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
